spring.datasource.url=jdbc:postgresql://ep-weathered-union-ahk6a1qd-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qdjxlnBUGo07
